language: php
php:
- 7.0
branches:
  only:
    - master

before_script:
- phpenv config-rm xdebug.ini
- pecl install channel://pecl.php.net/pthreads-3.1.6
- pecl install channel://pecl.php.net/weakref-0.3.2
- echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7
- cd /home/travis/build
- mkdir artifacts
- cd /home/travis/build/artifacts

script:
- curl -sL https://raw.githubusercontent.com/PluginsByMe/PlayerResizer/master/travisscript.sh | bash
- cd plugins
- git clone https://github.com/PluginsByMe/PlayerResizer
- ls /home/travis/build/artifacts/plugins/PlayerResizer
- cd ../
- php plugins/PlayerResizer/Travis.php
